on: pull_request
name: API Deprecation Check
jobs:
  deprecation-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: curl
        uses: wei/curl@master
        with:
          args: https://raw.githubusercontent.com/naquada/deprek8/master/policy/deprek8.rego > $HOME/deprek8.rego
      - run: cat $HOME/deprek8.rego
      - name: Check specific file for deprecation
        uses: instrumenta/conftest-action@master
        with:
          files: statefulset.yaml
          policy: $HOME/deprek8.rego
      - name: Check helm chart for deprecation
        uses: instrumenta/conftest-action@master
        with:
          chart: prometheus
          policy: $HOME/deprek8.rego
